from typing import Any

__version__: str

class ImageList:
    class Grayed:
        def __len__(self) -> int: ...
        def __iter__(self) -> Any: ...
        def __getitem__(self, item: int | str) -> Any: ...
    def __init__(self, resource_folder: str = '', image_size: tuple[int, int] = (16, 16), auto_load : bool = False) -> None: ...
    @property
    def blank_image(self) -> Any: ...
    @property
    def grayed(self) -> ImageList.Grayed: ...
    @property
    def image_size(self) -> tuple[int, int]: ...
    @property
    def keys(self) -> list[str]: ...
    @property
    def resource_folder(self) -> str: ...
    @resource_folder.setter
    def resource_folder(self, path: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, item: int | str | slice) -> Any: ...
    def add(self, image_file: str, key_name: str | None = None) -> bool: ...
    def clear(self) -> None: ...
    def contains_key(self, name: str) -> bool: ...
    def extend(self, image_list: ImageList) -> bool: ...
    def index_of_key(self, name: str) -> int: ...
    def remove_at(self, index: int) -> None: ...
    def remove_by_key(self, name: str) -> None: ...
    def set_key_name(self, index: int, name: str) -> None: ...
